# Generated by Django 6.0.1 on 2026-01-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('age_category', models.CharField(choices=[('kids_boy', 'Kids - Boy'), ('kids_girl', 'Kids - Girl'), ('kids_unisex', 'Kids - Unisex'), ('adults_men', 'Adults - Men'), ('adults_women', 'Adults - Women'), ('adults_unisex', 'Adults - Unisex'), ('all_age_men', 'All Age - Men'), ('all_age_women', 'All Age - Women'), ('all_age_unisex', 'All Age - Unisex')], max_length=20)),
                ('product_category', models.CharField(choices=[('cloth', 'Cloth'), ('jewellery', 'Jewellery')], max_length=20)),
                ('mrp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('fit_type', models.CharField(blank=True, max_length=100)),
                ('pattern_design', models.CharField(blank=True, max_length=100)),
                ('age_limits', models.TextField(blank=True, help_text='Example: Suitable for kids aged 4 to 7 years', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('common_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock_qty', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='public.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
