# Generated by Django 6.0.1 on 2026-04-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_productcategory_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_category',
            field=models.CharField(choices=[('baby_boy', 'Baby - Boy'), ('baby_girl', 'Baby - Girl'), ('baby_unisex', 'Baby - Unisex'), ('kids_boy', 'Kids - Boy'), ('kids_girl', 'Kids - Girl'), ('kids_unisex', 'Kids - Unisex'), ('adults_men', 'Adults - Men'), ('adults_women', 'Adults - Women'), ('adults_unisex', 'Adults - Unisex'), ('all_age_men', 'All Age - Men'), ('all_age_women', 'All Age - Women'), ('all_age_unisex', 'All Age - Unisex')], default='baby_unisex', max_length=20),
        ),
    ]
