# Generated by Django 6.0.1 on 2026-04-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_product_age_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age_limits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='common_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fit_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pattern_design',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Use it only when all variants have the same price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Use it only when all variants have the same mrp', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='products/')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='public.product')),
            ],
        ),
    ]
