# Generated by Django 6.0.1 on 2026-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_remove_product_age_limits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='◉ Separate features with new lines for better display on frontend.', null=True),
        ),
    ]
