# Generated by Django 6.0.1 on 2026-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_product_description_product_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color')},
        ),
    ]
