# Generated by Django 6.0.1 on 2026-04-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_rename_is_active_productvariant_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_guide',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
