# Generated by Django 6.0.1 on 2026-04-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_product_size_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='lowest_variant_mrp',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='lowest_variant_price',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=10, null=True),
        ),
    ]
