# Generated by Django 6.0.1 on 2026-04-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_productvariant_lowest_variant_mrp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='lowest_variant_mrp',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lowest_variant_price',
        ),
        migrations.AddField(
            model_name='product',
            name='lowest_variant_mrp',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lowest_variant_price',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=10, null=True),
        ),
    ]
