# Generated by Django 6.0.1 on 2026-04-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
