# Generated by Django 5.2.8 on 2026-04-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
