# Generated by Django 6.0.1 on 2026-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_alter_productcategory_slug'),
        ('user', '0002_order_variant_checkoutsession_checkoutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='checkoutitem',
            unique_together={('session', 'variant')},
        ),
    ]
