# Generated by Django 5.2.8 on 2026-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_checkoutsession_status_alter_address_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
