# Generated by Django 5.2.8 on 2026-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_checkoutsession_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
