# Generated by Django 5.2.8 on 2026-04-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_checkoutsession_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
