# Generated by Django 5.2.8 on 2026-07-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_checkoutsession_is_buy_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_charge',
            field=models.FloatField(default=0),
        ),
    ]
